# This file was generated by GoReleaser. DO NOT EDIT.
class Hcledit < Formula
  desc "A command line editor for HCL"
  homepage "https://github.com/minamijoyo/hcledit"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/minamijoyo/hcledit/releases/download/v0.0.2/hcledit_0.0.2_darwin_amd64.tar.gz"
    sha256 "a3b249bc8528265167de9c4374d9497ef1b0e3925d8c9d816e9699627a1400a7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/minamijoyo/hcledit/releases/download/v0.0.2/hcledit_0.0.2_linux_amd64.tar.gz"
      sha256 "966850cf72f9fcd6f71e717347090b1d9e9d3385de1ac6e975600f2a6bd1daa2"
    end
  end

  def install
    bin.install "hcledit"
  end

  test do
    system "#{bin}/hcledit version"
  end
end
