# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hcledit < Formula
  desc "A command line editor for HCL"
  homepage "https://github.com/minamijoyo/hcledit"
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/minamijoyo/hcledit/releases/download/v0.1.3/hcledit_0.1.3_darwin_amd64.tar.gz"
    sha256 "203e78dd930e250d84378866ee5e13bdd45f6451527ef28147dbc13653ec390d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/minamijoyo/hcledit/releases/download/v0.1.3/hcledit_0.1.3_linux_amd64.tar.gz"
    sha256 "c8f11a0ac60e648da03578016b73001dd4ed84361e32df06594174ff319c952b"
  end

  def install
    bin.install "hcledit"
  end

  test do
    system "#{bin}/hcledit version"
  end
end
